// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use k256::ecdsa::signature::Signer;
use k256::ecdsa::signature::Verifier;
use k256::ecdsa::{Signature, SigningKey, VerifyingKey};
use k256::SecretKey;
use methods::{RWZ_POF_GUEST_ELF, RWZ_POF_GUEST_ID};
use rand_core::OsRng;
use risc0_zkvm::{default_prover, ExecutorEnv};
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
struct DealInfo {
    amount: u64,
    deal_id: String,
    buyer: String,
}

#[derive(Debug, Serialize, Deserialize)]
struct SignedMessage {
    pubkey: Vec<u8>,
    message: DealInfo,
    signature: Vec<u8>,
}

fn create_signed_message(
    signing_key: &SigningKey,
    amount: u64,
    deal_id: String,
    buyer: String,
) -> SignedMessage {
    let deal_info = DealInfo {
        amount,
        deal_id,
        buyer,
    };

    // Serialize the message to sign
    let message_bytes = bincode::serialize(&deal_info).unwrap();

    // Sign the message with explicit type
    let signature: k256::ecdsa::Signature = signing_key.sign(&message_bytes);

    // Get the public key
    let verifying_key = VerifyingKey::from(signing_key);

    SignedMessage {
        pubkey: verifying_key.to_sec1_bytes().to_vec(),
        message: deal_info,
        signature: signature.to_bytes().to_vec(),
    }
}

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    // An executor environment describes the configurations for the zkVM
    // including program inputs.
    // An default ExecutorEnv can be created like so:
    // `let env = ExecutorEnv::builder().build().unwrap();`
    // However, this `env` does not have any inputs.
    //
    // To add guest input to the executor environment, use
    // ExecutorEnvBuilder::write().
    // To access this method, you'll need to use ExecutorEnv::builder(), which
    // creates an ExecutorEnvBuilder. When you're done adding input, call
    // ExecutorEnvBuilder::build().

    // For example:
    let input: u32 = 15 * u32::pow(2, 27) + 1;
    let env = ExecutorEnv::builder()
        .write(&input)
        .unwrap()
        .build()
        .unwrap();

    // Obtain the default prover.
    let prover = default_prover();

    // Proof information by proving the specified ELF binary.
    // This struct contains the receipt along with statistics about execution of the guest
    let prove_info = prover.prove(env, RWZ_POF_GUEST_ELF).unwrap();

    // extract the receipt.
    let receipt = prove_info.receipt;

    // TODO: Implement code for retrieving receipt journal here.

    // For example:
    let output: u32 = receipt.journal.decode().unwrap();

    // Print, notice, after committing to a journal, the private input became public
    println!(
        "Hello, world! I generated a proof of guest execution! {} is a public output from journal ",
        output
    );

    // The receipt was verified at the end of proving, but the below code is an
    // example of how someone else could verify this receipt.
    receipt.verify(RWZ_POF_GUEST_ID).unwrap();
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_signature_creation_and_verification() {
        // Generate a test key
        let signing_key = SigningKey::random(&mut OsRng);

        // Create a signed message
        let signed_msg = create_signed_message(
            &signing_key,
            500,
            "DEAL001".to_string(),
            "buyer1".to_string(),
        );

        // Verify the signature
        let message_bytes = bincode::serialize(&signed_msg.message).unwrap();
        let signature = Signature::from_slice(&signed_msg.signature).unwrap();
        let verifying_key = VerifyingKey::from_sec1_bytes(&signed_msg.pubkey).unwrap();

        // This will panic if verification fails
        verifying_key.verify(&message_bytes, &signature).unwrap();
    }

    #[test]
    fn test_invalid_signature_fails() {
        // Generate two different keys
        let signing_key = SigningKey::random(&mut OsRng);
        let wrong_key = SigningKey::random(&mut OsRng);

        // Create a signed message with first key
        let signed_msg = create_signed_message(
            &signing_key,
            500,
            "DEAL001".to_string(),
            "buyer1".to_string(),
        );

        // Try to verify with wrong key
        let message_bytes = bincode::serialize(&signed_msg.message).unwrap();
        let signature = Signature::from_slice(&signed_msg.signature).unwrap();
        let wrong_verifying_key = VerifyingKey::from(&wrong_key);

        // This should fail
        assert!(wrong_verifying_key
            .verify(&message_bytes, &signature)
            .is_err());
    }
}
